package com.classgo.backend.domain.enums;

public enum AchievementAction {
    COMPLETE_CHALLENGE,
    RECORD_CHALLENGE_SCORE,
    UPDATE_AVATAR,
    COMPLETE_PROFILE,
    VISIT_SECTION,
    USE_FEATURE,
    COMPLETE_ACTIVITY_TYPE,
    FIRST_TO_COMPLETE_CHALLENGE,
    TRIGGER_SPECIAL_EVENT,
    GRANT_MANUAL_ACHIEVEMENT
}
