package com.classgo.backend.domain.enums;

public enum AchievementFactType {
    COMPLETED_CHALLENGE,
    CHALLENGE_HIGH_SCORE,
    CHALLENGE_PERFECT,
    COMPLETED_WEEK,
    SECTION_VISITED,
    FEATURE_USED,
    ACTIVITY_TYPE_COMPLETED,
    PROFILE_COMPLETED,
    AVATAR_UPDATED_STUDENT,
    AVATAR_UPDATED_PARENT,
    FIRST_COMPLETION_AWARDED
}
